site_title: संस्कृत-साङ्गणकाः Sanskrit Programmers
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: sanskrit-coders
# this appears in the footer

github_editme_path: sanskrit-coders/site/blob/gh-pages/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.
# Must end with a slash.

# gitlab_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
# if you're using GitLab, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname: sanskrit-coders-site
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

google_analytics: UA-43258994-2
# if you have google-analytics ID, put it in. if not, edit this value to blank.

google_webmaster_verification_tag: <meta name="google-site-verification" content="33f1oqqMeFzIsi1CqZcWDNtPLOqxkEhEg6Sitg7h6d4" />
# if you don't have the above, edit this value to blank.

google_custom_search_code: "
<script>
  (function() {
    var cx = '003441740804712584864:hj_depehpoo';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>
"
# feedback_subject_line: Jekyll documentation theme

# feedback_email: tomjoht@gmail.com
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

feedback_text: "Email?"
# if you uncomment the previous line, it changes the Feedback text

feedback_link: "https://groups.google.com/forum/#!forum/sanskrit-programmers"
# if you uncomment the previous line, it changes where the feedback link points to
# Order matters below.
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
      permalink: /posts/:slug:output_ext
# these are defaults used for the frontmatter for these file types


sidebars:
- home_sidebar

description: Sanskrit programming/ processing/ publishing/ tools.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

# needed for sitemap.xml file only
url: http://sanskrit-coders.github.io
baseurl: "/site" # the subpath of your site, e.g. /blog

remote_theme: sanskrit-coders/sanskrit-documentation-theme

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
