printf -- "---\ntitle: Fix title!\n---\n"> pages/content/dicts.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/books.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/audio.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/apps/intro.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/apps/translations.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/apps/deep-reading.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/fonts.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/ocr/intro.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/ocr/corrections.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/law.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/wikis.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/content/offline-web.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/tips/license.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/tips/dev-tools.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/tips/py-unicode.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/astronomy.md
