printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/bases/books.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/bases/elders.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/bases/pratyaxa.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/tattvam/chit.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/tattvam/Rta.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/tattvam/deva.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/tattvam/purushaartha.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/tattvam/science-magic.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/tattvam/sublabeling.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/introduction.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/rituals.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/communal-support/introduction.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/communal-support/exclusivity.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/communal-support/distinctness.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/communal-support/guru.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/decoration.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/food.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/sexual-attractiveness.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/self-cultivation/presentations.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/dharma.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/dharma-fluid.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/aashrama.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/dharma-fluid.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan/genetics.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan/india-entry.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan/varna-theory.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan/varna-practice.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan/vanavaasii.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan/criticism.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan/varnavatii.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan/modern-caste-politics.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/clan/future.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/external-affairs/id.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/external-affairs/tolerance.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/external-affairs/defence.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/external-affairs/violence.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/women.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/intellect-sentiment.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/social-cultivation/subversion.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/resources/intro.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/abe-disease.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/islam/intro.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/islam/constituent-subversion.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/islam/kaafir-jihaad.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/zombie-cult.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/iyi/intro.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/iyi/secularism.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/academia/charges.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/academia/negationism.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/u-turn.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/rags.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/rivals/aananda-addiction.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/polity/desiderata.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/polity/sick-india-hindus.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/polity/sick-india-demographics.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/polity/geopolitics.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/polity/hindu-abroad.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/history/intro.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/history/places.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/history/heroes.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/history/heroes-alien.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/history/administration.md
printf -- "---\ntitle: Fix title!\n---\n"> pages/hindutvam/history/military.md

